### ISSUE TITLE
TPS monitor goes above 20

### ISSUE THREAD

**Issue by TheRealM18** [rater193/OpenComputers-OpenGlassesMonitor#1]
The is a current issue that the tps monitor will go above 20.  Not sure what causes this but here is some screenshots if this happening.

![2018-04-18_11 15 37](https://user-images.githubusercontent.com/5025664/38938214-686aa712-42fb-11e8-809f-07f97f626205.png)
![2018-04-18_11 15 42](https://user-images.githubusercontent.com/5025664/38938215-6881ce1a-42fb-11e8-9002-744639e39abc.png)
![2018-04-18_11 22 30](https://user-images.githubusercontent.com/5025664/38938216-689a5214-42fb-11e8-8041-f979034ba44c.png)

**Comment by rater193** [comment]
Fixed
